<?php

declare(strict_types=1);

// php/codegen/generate.php: the half of the PHP app kit openapi-generator
// does not write (ADR 30.9.26am D6). It reads the app view
// (spec/generator/apps.3.0.json) and writes into php/src/Generated/ (or
// <--out>/Generated/):
//
//   <Union>.php        one interface per x-lingara-unions entry: CardElement
//                      (tag `type`), ListItem (tag `type`), ContextSlice (tag
//                      `kind`), carrying the tag values as a constant list
//                      (TYPES, KINDS) and each value's arm (ARMS)
//   <Union><Tag>.php   one final readonly class per arm, with the arm's
//                      closed field set, implementing its union; it encodes
//                      with an unset optional member omitted, and a
//                      ContextSlice arm also decodes leniently (fromValue)
//   AppOperation.php   x-lingara-app-operations as a closed enum: the
//                      request messages, each one's request model, and the
//                      reply message
//
// openapi-generator writes the other models beside these, and
// codegen/php.openapi-generator-ignore keeps it from writing a union or an
// arm. A file there named after one, without this script's header, is the
// generator's: it is refused, since a new arm the ignore file does not cover
// would otherwise ship two classes for one name. Standard library only; not
// in the dist.

const HEADER = '// Generated by php/codegen/generate.php from the app view. DO NOT EDIT.';
const OPERATIONS = 'AppOperation';

function fail(string $message): never
{
    fwrite(STDERR, "generate.php: {$message}\n");
    exit(1);
}

function refName(?string $ref): ?string
{
    if ($ref === null) {
        return null;
    }
    $parts = explode('/', $ref);
    return end($parts);
}

function camel(string $name): string
{
    return lcfirst(str_replace(' ', '', ucwords(str_replace(['_', '-', '.'], ' ', $name))));
}

function export(mixed $value): string
{
    if (is_array($value) && array_is_list($value)) {
        return '[' . implode(', ', array_map('export', $value)) . ']';
    }
    return var_export($value, true);
}

/**
 * The view's unions: name, tag and arms (tag value => arm schema name), in
 * the view's order.
 *
 * @return list<array{name: string, tag: string, arms: array<string, string>}>
 */
function unions(array $view): array
{
    $unions = [];
    foreach ($view['x-lingara-unions'] ?? fail('the view has no x-lingara-unions') as $i => $entry) {
        $arms = [];
        foreach ($entry['arms'] ?? [] as $arm) {
            $arms[(string) $arm['value']] = refName($arm['schema'] ?? null) ?? fail("x-lingara-unions/{$i}: an arm has no schema");
        }
        $arms !== [] || fail("x-lingara-unions/{$i}: no arms");
        $unions[] = ['name' => (string) $entry['name'], 'tag' => (string) $entry['tag'], 'arms' => $arms];
    }
    return $unions;
}

/**
 * One property of an arm: its wire name, PHP name, PHP type, decode check
 * and whether it is optional (nullable, defaulting to null).
 *
 * @return array{wire: string, php: string, type: string, doc: ?string, scalar: ?string, optional: bool}
 */
function property(array $view, string $arm, string $wire, array $schema, bool $required): array
{
    $optional = !$required || ($schema['nullable'] ?? false);
    $ref = refName($schema['$ref'] ?? $schema['allOf'][0]['$ref'] ?? null);
    [$type, $doc, $scalar] = match (true) {
        $ref !== null => [$ref, null, null],
        ($schema['type'] ?? null) === 'string' => ['string', null, 'string'],
        ($schema['type'] ?? null) === 'integer' => ['int', null, 'int'],
        ($schema['type'] ?? null) === 'number' => ['float', null, 'float'],
        ($schema['type'] ?? null) === 'boolean' => ['bool', null, 'bool'],
        ($schema['type'] ?? null) === 'array' => ['array', 'list<' . (refName($schema['items']['$ref'] ?? null) ?? 'mixed') . '>', null],
        default => fail("{$arm}.{$wire}: a type this emitter does not map"),
    };
    isset($view['components']['schemas'][$ref ?? '']) || $ref === null || fail("{$arm}.{$wire}: no component {$ref}");
    return ['wire' => $wire, 'php' => camel($wire), 'type' => $type, 'doc' => $doc, 'scalar' => $scalar, 'optional' => $optional];
}

/**
 * An arm's properties without its tag: the required ones first, then the
 * optional ones, each in the view's order, so the constructor never puts an
 * optional parameter before a required one.
 *
 * @return list<array<string, mixed>>
 */
function armProperties(array $view, string $arm, string $tag): array
{
    $schema = $view['components']['schemas'][$arm] ?? fail("no component {$arm}");
    $required = $schema['required'] ?? [];
    $props = [];
    foreach ($schema['properties'] ?? [] as $wire => $prop) {
        if ($wire !== $tag) {
            $props[] = property($view, $arm, (string) $wire, $prop, in_array($wire, $required, true));
        }
    }
    usort($props, static fn(array $a, array $b): int => $a['optional'] <=> $b['optional']);
    return $props;
}

function unionPhp(array $union): string
{
    $header = HEADER;
    $const = strtoupper($union['tag']) . 'S';
    $values = export(array_map('strval', array_keys($union['arms'])));
    $rows = [];
    foreach ($union['arms'] as $value => $arm) {
        $rows[] = '        ' . export((string) $value) . " => {$arm}::class,";
    }
    $arms = implode("\n", $rows);
    return <<<PHP
        <?php

        {$header}

        declare(strict_types=1);

        namespace Lingara\\Apps\\Generated;

        /**
         * The `{$union['name']}` union, tagged on `{$union['tag']}`: one final class per arm.
         */
        interface {$union['name']} extends \\JsonSerializable
        {
            /** The tag member's name on the wire. */
            public const TAG = '{$union['tag']}';

            /** Every `{$union['tag']}` value, in the view's order. */
            public const {$const} = {$values};

            /**
             * Each `{$union['tag']}` value's arm.
             *
             * @var array<string, class-string<{$union['name']}>>
             */
            public const ARMS = [
        {$arms}
            ];
        }

        PHP;
}

/** @param list<array<string, mixed>> $props */
function constructorParams(array $props): string
{
    $lines = [];
    foreach ($props as $p) {
        $doc = $p['doc'] === null ? '' : "        /** @var {$p['doc']} */\n";
        $lines[] = $p['optional']
            ? "{$doc}        public ?{$p['type']} \${$p['php']} = null,"
            : "{$doc}        public {$p['type']} \${$p['php']},";
    }
    return implode("\n", $lines);
}

/** @param list<array<string, mixed>> $props */
function encodeRows(string $tag, array $props): string
{
    $rows = ["            '{$tag}' => \$this->{$tag},"];
    foreach ($props as $p) {
        $rows[] = "            '{$p['wire']}' => \$this->{$p['php']},";
    }
    return implode("\n", $rows);
}

/** The check that a decoded member fits a scalar property. */
function check(array $p): string
{
    $value = "\$v['{$p['wire']}']";
    $test = match ($p['scalar']) {
        'float' => "(is_int({$value}) || is_float({$value}))",
        default => "is_{$p['scalar']}({$value})",
    };
    return $p['optional'] ? "(({$value} ?? null) === null || {$test})" : "isset({$value}) && {$test}";
}

/** A ContextSlice arm's lenient decoder: unknown members ignored. */
function decoderPhp(string $arm, array $props): string
{
    $checks = [];
    $args = [];
    foreach ($props as $p) {
        $p['scalar'] !== null || fail("{$arm}.{$p['wire']}: a decoded arm holds scalars only");
        $checks[] = check($p);
        $cast = $p['scalar'] === 'float' ? '(float) ' : '';
        $args[] = match (true) {
            !$p['optional'] => "{$p['php']}: {$cast}\$v['{$p['wire']}']",
            $cast === '' => "{$p['php']}: \$v['{$p['wire']}'] ?? null",
            default => "{$p['php']}: isset(\$v['{$p['wire']}']) ? {$cast}\$v['{$p['wire']}'] : null",
        };
    }
    $condition = implode("\n            && ", $checks);
    $arguments = implode(",\n            ", $args);
    return <<<PHP


            /**
             * Decodes one slice of this kind, ignoring members it does not
             * know; null when a member it needs is absent or mistyped.
             */
            public static function fromValue(\\stdClass \$value): ?self
            {
                \$v = get_object_vars(\$value);
                if (!(
                    {$condition}
                )) {
                    return null;
                }
                return new self(
                    {$arguments},
                );
            }
        PHP;
}

function armPhp(array $view, array $union, string $value, string $arm): string
{
    $header = HEADER;
    $tag = $union['tag'];
    $props = armProperties($view, $arm, $tag);
    $params = constructorParams($props);
    $rows = encodeRows($tag, $props);
    $constructor = $params === '' ? "public function __construct()\n    " : "public function __construct(\n{$params}\n    ) ";
    $decoder = $union['name'] === 'ContextSlice' ? decoderPhp($arm, $props) : '';
    $exported = export($value);
    $const = strtoupper($tag);
    return <<<PHP
        <?php

        {$header}

        declare(strict_types=1);

        namespace Lingara\\Apps\\Generated;

        /** The `{$value}` arm of {$union['name']}. */
        final readonly class {$arm} implements {$union['name']}
        {
            public const {$const} = {$exported};

            /** Always `{$value}`. */
            public string \${$tag};

            {$constructor}{
                \$this->{$tag} = self::{$const};
            }

            /**
             * The wire form: an unset optional member is omitted, never null.
             *
             * @return array<string, mixed>
             */
            public function jsonSerialize(): array
            {
                return array_filter([
        {$rows}
                ], static fn(mixed \$member): bool => \$member !== null);
            }{$decoder}
        }

        PHP;
}

/**
 * The operations, from x-lingara-app-operations: case name => [message,
 * request model]. One reply message for all of them.
 *
 * @return array{cases: array<string, array{string, string}>, reply: string}
 */
function operations(array $view): array
{
    $cases = [];
    $replies = [];
    foreach ($view['x-lingara-app-operations'] ?? fail('the view has no x-lingara-app-operations') as $i => $op) {
        $message = (string) ($op['message'] ?? fail("x-lingara-app-operations/{$i}: no message"));
        $request = refName($op['request'] ?? null) ?? fail("x-lingara-app-operations/{$i}: no request");
        $case = strtoupper(str_replace(['app.', '.'], ['', '_'], $message));
        $cases[$case] = [$message, $request];
        $replies[] = (string) ($op['reply_message'] ?? fail("x-lingara-app-operations/{$i}: no reply_message"));
    }
    count(array_unique($replies)) === 1 || fail('the operations do not share one reply message');
    return ['cases' => $cases, 'reply' => $replies[0]];
}

function operationsPhp(array $ops): string
{
    $header = HEADER;
    $cases = [];
    $requests = [];
    foreach ($ops['cases'] as $case => [$message, $request]) {
        $cases[] = "    case {$case} = " . export($message) . ';';
        $requests[] = "            self::{$case} => {$request}::class,";
    }
    $caseLines = implode("\n", $cases);
    $requestLines = implode("\n", $requests);
    $reply = export($ops['reply']);
    return <<<PHP
        <?php

        {$header}

        declare(strict_types=1);

        namespace Lingara\\Apps\\Generated;

        /**
         * The app operations: each request's `type`, closed. A new operation in
         * the view adds a case here, and the kit's dispatch test fails until the
         * core handles it.
         */
        enum AppOperation: string
        {
        {$caseLines}

            /** The message every operation is answered with. */
            public const REPLY = {$reply};

            /** @return class-string<ModelInterface> the generated request model */
            public function request(): string
            {
                return match (\$this) {
        {$requestLines}
                };
            }
        }

        PHP;
}

/** @return array<string, string> file name under Generated/ => contents */
function files(array $view): array
{
    $files = [];
    foreach (unions($view) as $union) {
        $files["{$union['name']}.php"] = unionPhp($union);
        foreach ($union['arms'] as $value => $arm) {
            $files["{$arm}.php"] = armPhp($view, $union, (string) $value, $arm);
        }
    }
    $files[OPERATIONS . '.php'] = operationsPhp(operations($view));
    ksort($files, SORT_STRING);
    return $files;
}

function ours(string $file): bool
{
    $head = (string) file_get_contents($file, false, null, 0, 256);
    return str_contains($head, HEADER);
}

/**
 * A file named after a class this script writes that it did not write is
 * openapi-generator's: refuse it rather than ship two classes for one name.
 *
 * @param array<string, string> $files
 */
function refuseForeign(string $dir, array $files): void
{
    foreach (array_keys($files) as $name) {
        $file = "{$dir}/{$name}";
        if (file_exists($file) && !ours($file)) {
            fail("{$file} is openapi-generator's model named " . basename($name, '.php')
                . ', a class php/codegen/generate.php writes; name it in codegen/php.openapi-generator-ignore');
        }
    }
}

function main(): void
{
    $root = dirname(__DIR__, 2);
    $options = getopt('', ['out:', 'view:']);
    $out = rtrim((string) ($options['out'] ?? "{$root}/php/src"), '/');
    $viewFile = (string) ($options['view'] ?? "{$root}/spec/generator/apps.3.0.json");
    try {
        $view = json_decode((string) file_get_contents($viewFile), true, 512, JSON_THROW_ON_ERROR);
    } catch (JsonException $e) {
        fail("{$viewFile}: {$e->getMessage()}");
    }
    is_array($view) || fail("{$viewFile}: not an object");
    $dir = "{$out}/Generated";
    $files = files($view);
    refuseForeign($dir, $files);
    is_dir($dir) || mkdir($dir, 0o777, true);
    // A union or arm the view no longer has leaves no stale file behind.
    foreach (glob("{$dir}/*.php") ?: [] as $file) {
        if (!isset($files[basename($file)]) && ours($file)) {
            unlink($file);
        }
    }
    foreach ($files as $name => $text) {
        file_put_contents("{$dir}/{$name}", $text);
    }
}

main();
