package com.getlingara.codegen;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Writes what openapi-generator does not for the Java and Kotlin app kits (ADR 30.9.26am D6): the
 * three sealed unions of {@code x-lingara-unions} with their arms, each arm implementing its union;
 * the {@code ContextSlice} kinds as a closed constant list ({@code ContextSliceKind}); and the
 * operations of {@code x-lingara-app-operations} as a closed enum ({@code AppOperation}) with the
 * reply message beside it.
 *
 * <p>It reads the same view openapi-generator reads and runs after it in the same staging
 * directory. It refuses, naming the file, when openapi-generator wrote a file named after a union
 * or an arm: a fourth union the ignore file does not name then fails the build instead of shipping
 * two types for one name.
 *
 * <p>Usage: {@code AppsCodegen <view> <staged sources>} for Java, or {@code AppsCodegen --kotlin
 * <view> <staged sources>}.
 */
public final class AppsCodegen {
  static final String HEADER =
      "// Generated by :codegen's AppsCodegen from spec/generator/apps.3.0.json. Do not edit.\n";

  /** What differs between the two outputs: the model package, the extension and the renderer. */
  record Lang(String model, String extension, String ignoreFile, Renderer renderer) {
    static final Lang JAVA =
        new Lang("com.getlingara.apps.model", ".java", "java", new JavaAppsSource());
    static final Lang KOTLIN =
        new Lang("com.getlingara.apps.kotlin.model", ".kt", "kotlin", new KotlinAppsSource());
  }

  /** Renders one language's sources from the view's reading. */
  interface Renderer {
    String union(String pkg, Union union);

    String arm(String pkg, Union union, Arm arm);

    String kinds(String pkg, Union union);

    String operations(String pkg, List<Operation> operations);
  }

  /** One {@code x-lingara-unions} record: its name, its tag property and its arms, in order. */
  record Union(String name, String tag, List<Arm> arms) {}

  /** One arm: its tag value on the wire, its component name and its fields (the tag excluded). */
  record Arm(String value, String name, List<Field> fields) {}

  /**
   * One property of an arm. {@code type} is the view's type, abstracted: {@code string}, {@code
   * u8}, {@code u32}, {@code double}, {@code bool}, {@code ref:<Name>} or {@code list:<Name>}.
   */
  record Field(String json, String type, boolean optional) {
    /** The property's camelCase name. */
    String camel() {
      StringBuilder b = new StringBuilder();
      boolean upper = false;
      for (char c : json.toCharArray()) {
        if (c == '_') {
          upper = true;
        } else {
          b.append(upper ? Character.toUpperCase(c) : c);
          upper = false;
        }
      }
      return b.toString();
    }
  }

  /** One {@code x-lingara-app-operations} entry: the request message and the reply message. */
  record Operation(String message, String request, String replyMessage) {
    /** The enum constant: {@code app.render} is {@code APP_RENDER}. */
    String constant() {
      return message.replaceAll("[^A-Za-z0-9]", "_").toUpperCase(java.util.Locale.ROOT);
    }
  }

  private final JsonNode view;
  private final Path sources;
  private final Lang lang;

  AppsCodegen(JsonNode view, Path sources, Lang lang) {
    this.view = view;
    this.sources = sources;
    this.lang = lang;
  }

  /**
   * Runs the generator.
   *
   * @param args {@code [--kotlin] <view> <staged sources>}
   * @throws IOException when a file cannot be read or written
   */
  public static void main(String[] args) throws IOException {
    boolean kotlin = args.length == 3 && args[0].equals("--kotlin");
    if (!kotlin && args.length != 2) {
      throw new IllegalArgumentException("usage: AppsCodegen [--kotlin] <view> <staged sources>");
    }
    int at = kotlin ? 1 : 0;
    JsonNode view = new ObjectMapper().readTree(Path.of(args[at]).toFile());
    new AppsCodegen(view, Path.of(args[at + 1]), kotlin ? Lang.KOTLIN : Lang.JAVA).write();
  }

  /** Refuses a staged copy of any union or arm, then writes every file. */
  void write() throws IOException {
    List<Union> unions = unions();
    refuseGeneratorCopies(unions);
    Path models = sources.resolve(lang.model().replace('.', '/'));
    Renderer r = lang.renderer();
    for (Union u : unions) {
      writeFile(models.resolve(u.name() + lang.extension()), r.union(lang.model(), u));
      for (Arm a : u.arms()) {
        writeFile(models.resolve(a.name() + lang.extension()), r.arm(lang.model(), u, a));
      }
      if (u.name().equals("ContextSlice")) {
        writeFile(models.resolve("ContextSliceKind" + lang.extension()), r.kinds(lang.model(), u));
      }
    }
    writeFile(
        models.resolve("AppOperation" + lang.extension()),
        r.operations(lang.model(), operations()));
  }

  void refuseGeneratorCopies(List<Union> unions) {
    Path models = sources.resolve(lang.model().replace('.', '/'));
    for (Union u : unions) {
      List<String> names = new ArrayList<>();
      names.add(u.name());
      u.arms().forEach(a -> names.add(a.name()));
      for (String name : names) {
        Path file = models.resolve(name + lang.extension());
        if (Files.exists(file)) {
          throw new IllegalStateException(
              file
                  + " was written by openapi-generator, but "
                  + name
                  + " belongs to the app union "
                  + u.name()
                  + ": add a glob for it to codegen/"
                  + lang.ignoreFile()
                  + ".openapi-generator-ignore");
        }
      }
    }
  }

  /** Every union in the view, in its order. */
  List<Union> unions() {
    List<Union> out = new ArrayList<>();
    for (JsonNode entry : view.path("x-lingara-unions")) {
      String tag = entry.path("tag").asText();
      List<Arm> arms = new ArrayList<>();
      for (JsonNode arm : entry.path("arms")) {
        String name = refName(arm.path("schema").asText());
        arms.add(new Arm(arm.path("value").asText(), name, fields(schema(name), tag)));
      }
      out.add(new Union(entry.path("name").asText(), tag, List.copyOf(arms)));
    }
    return out;
  }

  /** Every operation in the view, in its order. */
  List<Operation> operations() {
    List<Operation> out = new ArrayList<>();
    for (JsonNode entry : view.path("x-lingara-app-operations")) {
      out.add(
          new Operation(
              entry.path("message").asText(),
              refName(entry.path("request").asText()),
              entry.path("reply_message").asText()));
    }
    return out;
  }

  private List<Field> fields(JsonNode schema, String tag) {
    List<String> required = new ArrayList<>();
    schema.path("required").forEach(r -> required.add(r.asText()));
    List<Field> out = new ArrayList<>();
    for (var p : schema.path("properties").properties()) {
      if (!p.getKey().equals(tag)) {
        JsonNode s = p.getValue();
        boolean optional = !required.contains(p.getKey()) || s.path("nullable").asBoolean(false);
        out.add(new Field(p.getKey(), type(s), optional));
      }
    }
    return List.copyOf(out);
  }

  static String type(JsonNode s) {
    if (s.has("$ref")) {
      return "ref:" + refName(s.path("$ref").asText());
    }
    if (s.has("allOf")) {
      return type(s.path("allOf").path(0));
    }
    String format = s.path("format").asText("");
    return switch (s.path("type").asText()) {
      case "string" -> "string";
      case "boolean" -> "bool";
      case "number" -> "double";
      case "integer" -> format.equals("uint8") ? "u8" : "u32";
      case "array" -> "list:" + refName(s.path("items").path("$ref").asText());
      default -> throw new IllegalStateException("AppsCodegen cannot type " + s);
    };
  }

  private JsonNode schema(String name) {
    JsonNode s = view.path("components").path("schemas").path(name);
    if (s.isMissingNode()) {
      throw new IllegalStateException("the view has no component " + name);
    }
    return s;
  }

  static String refName(String ref) {
    return ref.substring(ref.lastIndexOf('/') + 1);
  }

  static void writeFile(Path file, String text) throws IOException {
    Files.createDirectories(file.getParent());
    Files.writeString(file, text, StandardCharsets.UTF_8);
  }
}
