//! `lingara-apps-xtask`: writes `rust/src/generated/` from the app view
//! (ADR 30.9.26am D6).
//!
//! - `models.rs` is typify over every `components.schemas` entry. The three
//!   union components are replaced by the enums `unions.rs` writes, so typify
//!   never defines them, and each arm loses its tag property, which the
//!   union's `#[serde(tag = …)]` carries instead. Request-side types lose
//!   `deny_unknown_fields`, so a newer relay's extra field is ignored (AK2);
//! - `unions.rs` is written here from `x-lingara-unions` and
//!   `x-lingara-app-operations`, which typify does not read;
//! - `spec_version.rs` names the view's version; `mod.rs` allows clippy.
//!
//! Everything is rendered through prettyplease, so two runs are
//! byte-identical. `codegen [--out-dir <dir>]` writes; `check-codegen`
//! compares with the committed files instead.

mod typify_pass;
mod unions;
mod view;

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde_json::Value;

const VIEW: &str = "spec/generator/apps.3.1.json";
const OUT_DIR: &str = "rust/src/generated";
const HEADER: &str = "// Generated by lingara-apps-xtask from spec/generator/apps.3.1.json.\n\
                      // Do not edit: run `make codegen-rust`.\n\n";
const MOD_RS: &str = "#![allow(clippy::all)]\n\npub mod models;\npub mod spec_version;\npub mod unions;\n";

fn main() -> ExitCode {
    match run(std::env::args().skip(1).collect()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("✗ lingara-apps-xtask: {message}");
            ExitCode::FAILURE
        }
    }
}

fn run(args: Vec<String>) -> Result<(), String> {
    let usage = "usage: lingara-apps-xtask codegen [--out-dir <dir>] | check-codegen";
    let root = workspace_root();
    let mut args = args.into_iter();
    let (check, mut out) = match args.next().as_deref() {
        Some("codegen") => (false, root.join(OUT_DIR)),
        Some("check-codegen") => (true, root.join(OUT_DIR)),
        _ => return Err(usage.into()),
    };
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--out-dir" if !check => out = PathBuf::from(args.next().ok_or(usage)?),
            _ => return Err(usage.into()),
        }
    }
    let files = generate(&read_json(&root.join(VIEW))?)?;
    if check { compare(&out, &files) } else { write(&out, &files) }
}

/// This crate sits at `rust/xtask`, two below the workspace root.
fn workspace_root() -> PathBuf {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    root.canonicalize().unwrap_or(root)
}

fn read_json(path: &Path) -> Result<Value, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))
}

/// The four files, name and contents, in a fixed order.
pub(crate) fn generate(view: &Value) -> Result<Vec<(&'static str, String)>, String> {
    let read = view::read(view)?;
    let models = typify_pass::models(view, &read)?;
    let unions = render(unions::render(&read))?;
    Ok(vec![
        ("mod.rs", format!("{HEADER}{MOD_RS}")),
        ("models.rs", format!("{HEADER}{models}")),
        ("spec_version.rs", format!("{HEADER}{}", spec_version(view)?)),
        ("unions.rs", format!("{HEADER}{unions}")),
    ])
}

fn spec_version(view: &Value) -> Result<String, String> {
    let id = view.pointer("/info/version").and_then(Value::as_str).ok_or("the view has no info.version")?;
    Ok(format!("/// The app view this crate's types were generated from.\npub const GENERATED_FOR_VERSION: &str = {id:?};\n"))
}

fn render(tokens: proc_macro2::TokenStream) -> Result<String, String> {
    let file: syn::File = syn::parse2(tokens).map_err(|e| format!("generated code does not parse: {e}"))?;
    Ok(prettyplease::unparse(&file))
}

fn write(out: &Path, files: &[(&str, String)]) -> Result<(), String> {
    std::fs::create_dir_all(out).map_err(|e| format!("{}: {e}", out.display()))?;
    for (name, contents) in files {
        let path = out.join(name);
        std::fs::write(&path, contents).map_err(|e| format!("{}: {e}", path.display()))?;
    }
    println!("✓ wrote {} files to {}", files.len(), out.display());
    Ok(())
}

fn compare(out: &Path, files: &[(&str, String)]) -> Result<(), String> {
    let stale: Vec<&str> = files
        .iter()
        .filter(|(name, contents)| std::fs::read_to_string(out.join(name)).ok().as_deref() != Some(contents.as_str()))
        .map(|(name, _)| *name)
        .collect();
    if !stale.is_empty() {
        return Err(format!("{} is stale ({}): run make codegen-rust", out.display(), stale.join(", ")));
    }
    println!("✓ {} is current", out.display());
    Ok(())
}
