# Generated by ruby/codegen/generate.rb from the app view. DO NOT EDIT.

module Lingara
  module Apps
    # The view's x-lingara-app-operations: the request messages a kit
    # dispatches on (a request's `type`) and the reply message. The core's
    # dispatch table is held to REQUESTS' keys by a unit test, so a third
    # operation fails the build until the core handles it.
    module Operations
      RENDER = "app.render"
      ACTION = "app.action"

      # Each request message and the name of its generated request model.
      REQUESTS = {
        "app.render" => "AppRenderRequest",
        "app.action" => "AppActionRequest"
      }.freeze

      # The reply every request expects: a card.
      REPLY = "app.card"
    end
  end
end
