# Generated by ruby/codegen/generate.rb from the app view. DO NOT EDIT.

module Lingara
  module Apps
    # The helpers every arm below shares.
    module Unions
      # An arm's wire form: its tag, then every member that is set (an
      # unset optional member is omitted, never null), nested arms in
      # their own wire form.
      def self.wire(tag, value, members)
        members.compact.each_with_object({tag => value}) do |(name, member), out|
          out[name.to_s] = member.is_a?(Array) ? member.map { |m| m.respond_to?(:to_wire) ? m.to_wire : m } : member
        end
      end

      # The keyword arguments for an arm, read from a decoded JSON
      # object: its own members only (an unknown key is ignored), null
      # treated as absent. A missing required member is ArgumentError.
      def self.members(arm, fields)
        arm.members.to_h { |m| [m, fields[m.to_s]] }.compact
      end
    end

    # A ContextSlice, tagged on `kind`: every arm includes this module, so
    # `case x in Lingara::Apps::ContextSlice` matches any of them.
    module ContextSlice
    end

    # A CardElement, tagged on `type`: every arm includes this module, so
    # `case x in Lingara::Apps::CardElement` matches any of them.
    module CardElement
    end

    # A ListItem, tagged on `type`: every arm includes this module, so
    # `case x in Lingara::Apps::ListItem` matches any of them.
    module ListItem
    end

    # The ContextSlice arm `languages`.
    ContextSliceLanguages = Data.define(:source_lang, :target_lang, :level) do
      include ContextSlice

      def initialize(source_lang:, target_lang:, level: nil)
        super
      end

      def kind = "languages"

      def to_wire = Unions.wire("kind", "languages", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The ContextSlice arm `plan_summary`.
    ContextSlicePlanSummary = Data.define(:plan_id, :target_lang, :set_count, :sets_completed, :title) do
      include ContextSlice

      def initialize(plan_id:, target_lang:, set_count:, sets_completed:, title: nil)
        super
      end

      def kind = "plan_summary"

      def to_wire = Unions.wire("kind", "plan_summary", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The ContextSlice arm `review_due`.
    ContextSliceReviewDue = Data.define(:due, :learned) do
      include ContextSlice

      def kind = "review_due"

      def to_wire = Unions.wire("kind", "review_due", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The ContextSlice arm `tutor_topic`.
    ContextSliceTutorTopic = Data.define(:topic) do
      include ContextSlice

      def kind = "tutor_topic"

      def to_wire = Unions.wire("kind", "tutor_topic", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `heading`.
    CardElementHeading = Data.define(:text, :level) do
      include CardElement

      def type = "heading"

      def to_wire = Unions.wire("type", "heading", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `text`.
    CardElementText = Data.define(:text, :lang) do
      include CardElement

      def initialize(text:, lang: nil)
        super
      end

      def type = "text"

      def to_wire = Unions.wire("type", "text", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `term`.
    CardElementTerm = Data.define(:word, :reading, :gloss, :lang) do
      include CardElement

      def initialize(word:, reading: nil, gloss: nil, lang: nil)
        super
      end

      def type = "term"

      def to_wire = Unions.wire("type", "term", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `list`.
    CardElementList = Data.define(:items) do
      include CardElement

      def type = "list"

      def to_wire = Unions.wire("type", "list", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `progress`.
    CardElementProgress = Data.define(:value, :label) do
      include CardElement

      def type = "progress"

      def to_wire = Unions.wire("type", "progress", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `divider`.
    CardElementDivider = Data.define() do
      include CardElement

      def type = "divider"

      def to_wire = Unions.wire("type", "divider", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `button`.
    CardElementButton = Data.define(:label, :action, :style) do
      include CardElement

      def initialize(label:, action:, style: nil)
        super
      end

      def type = "button"

      def to_wire = Unions.wire("type", "button", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The CardElement arm `link`.
    CardElementLink = Data.define(:label, :url) do
      include CardElement

      def type = "link"

      def to_wire = Unions.wire("type", "link", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The ListItem arm `text`.
    ListItemText = Data.define(:text, :lang) do
      include ListItem

      def initialize(text:, lang: nil)
        super
      end

      def type = "text"

      def to_wire = Unions.wire("type", "text", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    # The ListItem arm `term`.
    ListItemTerm = Data.define(:word, :reading, :gloss, :lang) do
      include ListItem

      def initialize(word:, reading: nil, gloss: nil, lang: nil)
        super
      end

      def type = "term"

      def to_wire = Unions.wire("type", "term", to_h)

      def self.from_wire(fields) = new(**Unions.members(self, fields))
    end

    module ContextSlice
      TAG = "kind"

      # Each tag value's arm.
      ARMS = {
        "languages" => ContextSliceLanguages,
        "plan_summary" => ContextSlicePlanSummary,
        "review_due" => ContextSliceReviewDue,
        "tutor_topic" => ContextSliceTutorTopic
      }.freeze

      # The arm a decoded JSON object names, or nil for a tag this kit does
      # not know. A known arm missing a required member is ArgumentError.
      def self.decode(fields)
        arm = ARMS[fields[TAG]]
        arm&.from_wire(fields)
      end
    end

    module CardElement
      TAG = "type"

      # Each tag value's arm.
      ARMS = {
        "heading" => CardElementHeading,
        "text" => CardElementText,
        "term" => CardElementTerm,
        "list" => CardElementList,
        "progress" => CardElementProgress,
        "divider" => CardElementDivider,
        "button" => CardElementButton,
        "link" => CardElementLink
      }.freeze

      # The arm a decoded JSON object names, or nil for a tag this kit does
      # not know. A known arm missing a required member is ArgumentError.
      def self.decode(fields)
        arm = ARMS[fields[TAG]]
        arm&.from_wire(fields)
      end
    end

    module ListItem
      TAG = "type"

      # Each tag value's arm.
      ARMS = {
        "text" => ListItemText,
        "term" => ListItemTerm
      }.freeze

      # The arm a decoded JSON object names, or nil for a tag this kit does
      # not know. A known arm missing a required member is ArgumentError.
      def self.decode(fields)
        arm = ARMS[fields[TAG]]
        arm&.from_wire(fields)
      end
    end

    # The ContextSlice tag values, in the view's order: what a manifest's
    # `context` may name.
    CONTEXT_SLICE_KINDS = ["languages", "plan_summary", "review_due", "tutor_topic"].freeze
  end
end
