# Generated by ruby/codegen/generate.rb from the app view. DO NOT EDIT.

module Lingara
  module Apps
    # This kit's released version, SemVer.
    VERSION = "0.1.0-alpha.6"

    # The same version in RubyGems' spelling, which the gemspec uses.
    GEM_VERSION = "0.1.0.pre.alpha.6"

    # The API version the app view was generated from.
    GENERATED_FROM = "2026-10-affable-towhee"
  end
end
