// Command codegen writes the Go app kit's apps_gen.go (ADR 30.9.26am D6).
// oapi-codegen writes the models from the app view, but its oneOf output
// would import its runtime package, and it reads neither x-lingara-unions
// nor x-lingara-app-operations. So this reads the same 3.0 view and writes,
// through go/format:
//
//   - each x-lingara-unions entry as a sealed interface, with the marker
//     method on each of oapi-codegen's arm structs;
//   - the ContextSlice kinds as a closed constant set, and the decoder the
//     handler core runs per slice;
//   - x-lingara-app-operations as the closed Operation constant set, and the
//     reply message beside it.
//
// It refuses a models file that already declares a name it writes, and one
// that lacks an arm, so a new arm can never ship two types for one name.
// It has no dependency, like the kit it writes.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// header opens apps_gen.go. The phrase is Go's convention for a generated
// file, which linters and gofmt checks recognise.
const header = "// Code generated by go/codegen from the app view (spec/generator/apps.3.0.json). DO NOT EDIT.\n\npackage lingaraapps\n"

// sliceUnion is the union whose tag values are the manifest's context kinds
// and whose elements the handler core decodes one by one (ADR 30.9.26am D4).
const sliceUnion = "ContextSlice"

type view struct {
	Unions     []union     `json:"x-lingara-unions"`
	Operations []operation `json:"x-lingara-app-operations"`
	Components struct {
		Schemas map[string]schema `json:"schemas"`
	} `json:"components"`
}

type union struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
	Arms []struct {
		Value  string `json:"value"`
		Schema string `json:"schema"`
	} `json:"arms"`
}

type operation struct {
	Operation    string `json:"operation"`
	Message      string `json:"message"`
	Request      string `json:"request"`
	ReplyMessage string `json:"reply_message"`
}

type schema struct {
	Properties map[string]struct {
		Enum []string `json:"enum"`
	} `json:"properties"`
}

// arm is one union arm as apps_gen.go writes it.
type arm struct{ value, typeName string }

func main() {
	viewPath := flag.String("view", "", "the 3.0 app view")
	modelsPath := flag.String("models", "", "oapi-codegen's models file, checked for names this writes")
	out := flag.String("out", "", "the directory to write apps_gen.go into")
	flag.Parse()
	if *viewPath == "" || *modelsPath == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: codegen -view <apps.3.0.json> -models <models_gen.go> -out <dir>")
		os.Exit(2)
	}
	src, err := generate(*viewPath, *modelsPath)
	if err == nil {
		err = os.WriteFile(filepath.Join(*out, "apps_gen.go"), src, 0o644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "✗ codegen:", err)
		os.Exit(1)
	}
}

// generate returns apps_gen.go's formatted bytes.
func generate(viewPath, modelsPath string) ([]byte, error) {
	raw, err := os.ReadFile(viewPath)
	if err != nil {
		return nil, err
	}
	var v view
	if err := json.Unmarshal(raw, &v); err != nil {
		return nil, fmt.Errorf("%s: %w", viewPath, err)
	}
	models, err := os.ReadFile(modelsPath)
	if err != nil {
		return nil, err
	}
	arms, err := collectArms(&v)
	if err != nil {
		return nil, err
	}
	if err := checkModels(string(models), &v, arms); err != nil {
		return nil, err
	}
	if len(v.Operations) == 0 {
		return nil, fmt.Errorf("%s: no x-lingara-app-operations", viewPath)
	}
	src := source(&v, arms)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("apps_gen.go: %w", err)
	}
	return formatted, nil
}

// collectArms reads each union's arms, checking that every arm's schema is
// a component whose tag property is the one value the union maps to it.
func collectArms(v *view) (map[string][]arm, error) {
	if len(v.Unions) == 0 {
		return nil, fmt.Errorf("no x-lingara-unions")
	}
	arms := map[string][]arm{}
	for _, u := range v.Unions {
		for _, a := range u.Arms {
			name := refName(a.Schema)
			s, ok := v.Components.Schemas[name]
			if !ok {
				return nil, fmt.Errorf("%s: arm %q is not a component", u.Name, name)
			}
			if enum := s.Properties[u.Tag].Enum; len(enum) != 1 || enum[0] != a.Value {
				return nil, fmt.Errorf("%s: arm %s's %s is not exactly %q", u.Name, name, u.Tag, a.Value)
			}
			arms[u.Name] = append(arms[u.Name], arm{a.Value, name})
		}
	}
	if len(arms[sliceUnion]) == 0 {
		return nil, fmt.Errorf("x-lingara-unions has no %s", sliceUnion)
	}
	return arms, nil
}

// written is every top-level name apps_gen.go declares.
func written(v *view, arms map[string][]arm) []string {
	names := []string{"Operation", "Operations", "ReplyMessage", "ContextSliceKind", "ContextSliceKinds", "decodeContextSlice"}
	for _, u := range v.Unions {
		names = append(names, u.Name)
	}
	for _, a := range arms[sliceUnion] {
		names = append(names, "ContextSliceKind"+camel(a.value))
	}
	for _, op := range v.Operations {
		names = append(names, "Operation"+camel(op.Message))
	}
	return names
}

// checkModels refuses a models file that declares a name apps_gen.go
// writes (a union the generator was not told to exclude, say), and one
// that lacks an arm the marker methods need.
func checkModels(models string, v *view, arms map[string][]arm) error {
	for _, name := range written(v, arms) {
		if declares(models, name) {
			return fmt.Errorf("the models file declares %s, which apps_gen.go writes: add it to exclude-schemas", name)
		}
	}
	for _, u := range v.Unions {
		for _, a := range arms[u.Name] {
			if !declares(models, a.typeName) {
				return fmt.Errorf("%s: the models file has no arm %s", u.Name, a.typeName)
			}
		}
	}
	return nil
}

// declares reports whether Go source declares a type, const, var or func
// named name at the top level.
func declares(src, name string) bool {
	q := regexp.QuoteMeta(name)
	re := regexp.MustCompile(`(?m)^(type|func|var|const)\s+` + q + `\b|^\s+` + q + `\s+\S+\s*=`)
	return re.MatchString(src)
}

// refName is the last segment of a `#/components/schemas/<Name>` reference.
func refName(ref string) string {
	return ref[strings.LastIndex(ref, "/")+1:]
}

// camel spells a wire value as a Go identifier: plan_summary is PlanSummary
// and app.render is AppRender.
func camel(value string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(value, func(r rune) bool { return r == '_' || r == '.' || r == '-' }) {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func source(v *view, arms map[string][]arm) string {
	var b strings.Builder
	b.WriteString(header + "\nimport \"encoding/json\"\n")
	for _, u := range v.Unions {
		writeUnion(&b, u, arms[u.Name])
	}
	writeSliceKinds(&b, arms[sliceUnion])
	writeOperations(&b, v.Operations)
	return b.String()
}

func writeUnion(b *strings.Builder, u union, arms []arm) {
	fmt.Fprintf(b, "\n// %s is one of the arms below, tagged on %q on the wire: type-switch on\n// its concrete arm. The set is sealed.\n", u.Name, u.Tag)
	fmt.Fprintf(b, "type %s interface{ is%s() }\n\n", u.Name, u.Name)
	for _, a := range arms {
		fmt.Fprintf(b, "func (%s) is%s() {} // %s: %q\n", a.typeName, u.Name, u.Tag, a.value)
	}
}

func writeSliceKinds(b *strings.Builder, arms []arm) {
	b.WriteString("\n// ContextSliceKind is a ContextSlice's kind: the closed set a manifest's\n// context may ask for.\ntype ContextSliceKind string\n\nconst (\n")
	for _, a := range arms {
		fmt.Fprintf(b, "\tContextSliceKind%s ContextSliceKind = %q\n", camel(a.value), a.value)
	}
	b.WriteString(")\n\n// ContextSliceKinds is every kind this kit was generated with, in the view's order.\nfunc ContextSliceKinds() []ContextSliceKind {\n\treturn []ContextSliceKind{")
	for i, a := range arms {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "ContextSliceKind%s", camel(a.value))
	}
	b.WriteString("}\n}\n")
	b.WriteString("\n// decodeContextSlice decodes one slice by its kind. An unknown kind is\n// false, never an error: a newer Lingara may send one.\n")
	b.WriteString("func decodeContextSlice(kind string, raw []byte) (ContextSlice, bool, error) {\n\tswitch kind {\n")
	for _, a := range arms {
		// The error is taken first: Go leaves unspecified whether `s` in a
		// return list is read before or after a call beside it.
		fmt.Fprintf(b, "\tcase %q:\n\t\tvar s %s\n\t\terr := json.Unmarshal(raw, &s)\n\t\treturn s, true, err\n", a.value, a.typeName)
	}
	b.WriteString("\t}\n\treturn nil, false, nil\n}\n")
}

func writeOperations(b *strings.Builder, ops []operation) {
	b.WriteString("\n// Operation is a request's type: the closed set of messages Lingara sends\n// an app. Each is answered with ReplyMessage.\ntype Operation string\n\nconst (\n")
	for _, op := range ops {
		fmt.Fprintf(b, "\t// Operation%s's body is %s.\n\tOperation%s Operation = %q\n", camel(op.Message), refName(op.Request), camel(op.Message), op.Message)
	}
	b.WriteString(")\n\n// Operations is every operation this kit was generated with, in the view's order.\nfunc Operations() []Operation {\n\treturn []Operation{")
	for i, op := range ops {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "Operation%s", camel(op.Message))
	}
	fmt.Fprintf(b, "}\n}\n\n// ReplyMessage is the message every operation is answered with.\nconst ReplyMessage = %q\n", ops[0].ReplyMessage)
}
