// Code generated by go/codegen from the app view (spec/generator/apps.3.0.json). DO NOT EDIT.

package lingaraapps

import "encoding/json"

// ContextSlice is one of the arms below, tagged on "kind" on the wire: type-switch on
// its concrete arm. The set is sealed.
type ContextSlice interface{ isContextSlice() }

func (ContextSliceLanguages) isContextSlice()   {} // kind: "languages"
func (ContextSlicePlanSummary) isContextSlice() {} // kind: "plan_summary"
func (ContextSliceReviewDue) isContextSlice()   {} // kind: "review_due"
func (ContextSliceTutorTopic) isContextSlice()  {} // kind: "tutor_topic"

// CardElement is one of the arms below, tagged on "type" on the wire: type-switch on
// its concrete arm. The set is sealed.
type CardElement interface{ isCardElement() }

func (CardElementHeading) isCardElement()  {} // type: "heading"
func (CardElementText) isCardElement()     {} // type: "text"
func (CardElementTerm) isCardElement()     {} // type: "term"
func (CardElementList) isCardElement()     {} // type: "list"
func (CardElementProgress) isCardElement() {} // type: "progress"
func (CardElementDivider) isCardElement()  {} // type: "divider"
func (CardElementButton) isCardElement()   {} // type: "button"
func (CardElementLink) isCardElement()     {} // type: "link"

// ListItem is one of the arms below, tagged on "type" on the wire: type-switch on
// its concrete arm. The set is sealed.
type ListItem interface{ isListItem() }

func (ListItemText) isListItem() {} // type: "text"
func (ListItemTerm) isListItem() {} // type: "term"

// ContextSliceKind is a ContextSlice's kind: the closed set a manifest's
// context may ask for.
type ContextSliceKind string

const (
	ContextSliceKindLanguages   ContextSliceKind = "languages"
	ContextSliceKindPlanSummary ContextSliceKind = "plan_summary"
	ContextSliceKindReviewDue   ContextSliceKind = "review_due"
	ContextSliceKindTutorTopic  ContextSliceKind = "tutor_topic"
)

// ContextSliceKinds is every kind this kit was generated with, in the view's order.
func ContextSliceKinds() []ContextSliceKind {
	return []ContextSliceKind{ContextSliceKindLanguages, ContextSliceKindPlanSummary, ContextSliceKindReviewDue, ContextSliceKindTutorTopic}
}

// decodeContextSlice decodes one slice by its kind. An unknown kind is
// false, never an error: a newer Lingara may send one.
func decodeContextSlice(kind string, raw []byte) (ContextSlice, bool, error) {
	switch kind {
	case "languages":
		var s ContextSliceLanguages
		err := json.Unmarshal(raw, &s)
		return s, true, err
	case "plan_summary":
		var s ContextSlicePlanSummary
		err := json.Unmarshal(raw, &s)
		return s, true, err
	case "review_due":
		var s ContextSliceReviewDue
		err := json.Unmarshal(raw, &s)
		return s, true, err
	case "tutor_topic":
		var s ContextSliceTutorTopic
		err := json.Unmarshal(raw, &s)
		return s, true, err
	}
	return nil, false, nil
}

// Operation is a request's type: the closed set of messages Lingara sends
// an app. Each is answered with ReplyMessage.
type Operation string

const (
	// OperationAppRender's body is AppRenderRequest.
	OperationAppRender Operation = "app.render"
	// OperationAppAction's body is AppActionRequest.
	OperationAppAction Operation = "app.action"
)

// Operations is every operation this kit was generated with, in the view's order.
func Operations() []Operation {
	return []Operation{OperationAppRender, OperationAppAction}
}

// ReplyMessage is the message every operation is answered with.
const ReplyMessage = "app.card"
