// Package lingaraapps provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package lingaraapps

// Defines values for AppSlotName.
const (
	AppSlotNameHomeSide         AppSlotName = "home.side"
	AppSlotNamePlansEmptyDetail AppSlotName = "plans.empty_detail"
)

// Valid indicates whether the value is a known member of the AppSlotName enum.
func (e AppSlotName) Valid() bool {
	switch e {
	case AppSlotNameHomeSide:
		return true
	case AppSlotNamePlansEmptyDetail:
		return true
	default:
		return false
	}
}

// Defines values for ButtonStyle.
const (
	ButtonStylePrimary   ButtonStyle = "primary"
	ButtonStyleSecondary ButtonStyle = "secondary"
)

// Valid indicates whether the value is a known member of the ButtonStyle enum.
func (e ButtonStyle) Valid() bool {
	switch e {
	case ButtonStylePrimary:
		return true
	case ButtonStyleSecondary:
		return true
	default:
		return false
	}
}

// Defines values for CardElementButtonType.
const (
	CardElementButtonTypeButton CardElementButtonType = "button"
)

// Valid indicates whether the value is a known member of the CardElementButtonType enum.
func (e CardElementButtonType) Valid() bool {
	switch e {
	case CardElementButtonTypeButton:
		return true
	default:
		return false
	}
}

// Defines values for CardElementDividerType.
const (
	CardElementDividerTypeDivider CardElementDividerType = "divider"
)

// Valid indicates whether the value is a known member of the CardElementDividerType enum.
func (e CardElementDividerType) Valid() bool {
	switch e {
	case CardElementDividerTypeDivider:
		return true
	default:
		return false
	}
}

// Defines values for CardElementHeadingType.
const (
	CardElementHeadingTypeHeading CardElementHeadingType = "heading"
)

// Valid indicates whether the value is a known member of the CardElementHeadingType enum.
func (e CardElementHeadingType) Valid() bool {
	switch e {
	case CardElementHeadingTypeHeading:
		return true
	default:
		return false
	}
}

// Defines values for CardElementLinkType.
const (
	CardElementLinkTypeLink CardElementLinkType = "link"
)

// Valid indicates whether the value is a known member of the CardElementLinkType enum.
func (e CardElementLinkType) Valid() bool {
	switch e {
	case CardElementLinkTypeLink:
		return true
	default:
		return false
	}
}

// Defines values for CardElementListType.
const (
	CardElementListTypeList CardElementListType = "list"
)

// Valid indicates whether the value is a known member of the CardElementListType enum.
func (e CardElementListType) Valid() bool {
	switch e {
	case CardElementListTypeList:
		return true
	default:
		return false
	}
}

// Defines values for CardElementProgressType.
const (
	CardElementProgressTypeProgress CardElementProgressType = "progress"
)

// Valid indicates whether the value is a known member of the CardElementProgressType enum.
func (e CardElementProgressType) Valid() bool {
	switch e {
	case CardElementProgressTypeProgress:
		return true
	default:
		return false
	}
}

// Defines values for CardElementTermType.
const (
	CardElementTermTypeTerm CardElementTermType = "term"
)

// Valid indicates whether the value is a known member of the CardElementTermType enum.
func (e CardElementTermType) Valid() bool {
	switch e {
	case CardElementTermTypeTerm:
		return true
	default:
		return false
	}
}

// Defines values for CardElementTextType.
const (
	CardElementTextTypeText CardElementTextType = "text"
)

// Valid indicates whether the value is a known member of the CardElementTextType enum.
func (e CardElementTextType) Valid() bool {
	switch e {
	case CardElementTextTypeText:
		return true
	default:
		return false
	}
}

// Defines values for ContextSliceLanguagesKind.
const (
	ContextSliceLanguagesKindLanguages ContextSliceLanguagesKind = "languages"
)

// Valid indicates whether the value is a known member of the ContextSliceLanguagesKind enum.
func (e ContextSliceLanguagesKind) Valid() bool {
	switch e {
	case ContextSliceLanguagesKindLanguages:
		return true
	default:
		return false
	}
}

// Defines values for ContextSlicePlanSummaryKind.
const (
	ContextSlicePlanSummaryKindPlanSummary ContextSlicePlanSummaryKind = "plan_summary"
)

// Valid indicates whether the value is a known member of the ContextSlicePlanSummaryKind enum.
func (e ContextSlicePlanSummaryKind) Valid() bool {
	switch e {
	case ContextSlicePlanSummaryKindPlanSummary:
		return true
	default:
		return false
	}
}

// Defines values for ContextSliceReviewDueKind.
const (
	ContextSliceReviewDueKindReviewDue ContextSliceReviewDueKind = "review_due"
)

// Valid indicates whether the value is a known member of the ContextSliceReviewDueKind enum.
func (e ContextSliceReviewDueKind) Valid() bool {
	switch e {
	case ContextSliceReviewDueKindReviewDue:
		return true
	default:
		return false
	}
}

// Defines values for ContextSliceTutorTopicKind.
const (
	ContextSliceTutorTopicKindTutorTopic ContextSliceTutorTopicKind = "tutor_topic"
)

// Valid indicates whether the value is a known member of the ContextSliceTutorTopicKind enum.
func (e ContextSliceTutorTopicKind) Valid() bool {
	switch e {
	case ContextSliceTutorTopicKindTutorTopic:
		return true
	default:
		return false
	}
}

// Defines values for ListItemTermType.
const (
	ListItemTermTypeTerm ListItemTermType = "term"
)

// Valid indicates whether the value is a known member of the ListItemTermType enum.
func (e ListItemTermType) Valid() bool {
	switch e {
	case ListItemTermTypeTerm:
		return true
	default:
		return false
	}
}

// Defines values for ListItemTextType.
const (
	ListItemTextTypeText ListItemTextType = "text"
)

// Valid indicates whether the value is a known member of the ListItemTextType enum.
func (e ListItemTextType) Valid() bool {
	switch e {
	case ListItemTextTypeText:
		return true
	default:
		return false
	}
}

// AppActionRequest defines model for AppActionRequest.
type AppActionRequest struct {
	ActionID  string         `json:"action_id"`
	CardEtag  string         `json:"card_etag"`
	Context   []ContextSlice `json:"context"`
	ID        string         `json:"id"`
	InstallID string         `json:"install_id"`
	Locale    string         `json:"locale"`
	Slot      AppSlotName    `json:"slot"`
	Subject   string         `json:"subject"`
	Type      string         `json:"type"`
}

// AppCardReply defines model for AppCardReply.
type AppCardReply struct {
	Card      Card    `json:"card"`
	TutorNote *string `json:"tutor_note,omitempty"`
}

// AppRenderRequest defines model for AppRenderRequest.
type AppRenderRequest struct {
	Context   []ContextSlice `json:"context"`
	ID        string         `json:"id"`
	InstallID string         `json:"install_id"`
	Locale    string         `json:"locale"`
	Slot      AppSlotName    `json:"slot"`
	Subject   string         `json:"subject"`
	Type      string         `json:"type"`
}

// AppSlotName defines model for AppSlotName.
type AppSlotName string

// ButtonStyle defines model for ButtonStyle.
type ButtonStyle string

// Card defines model for Card.
type Card struct {
	Elements []CardElement `json:"elements"`
}

// CardElementButton defines model for CardElementButton.
type CardElementButton struct {
	Action string                `json:"action"`
	Label  string                `json:"label"`
	Style  *ButtonStyle          `json:"style,omitempty"`
	Type   CardElementButtonType `json:"type"`
}

// CardElementButtonType defines model for CardElementButton.Type.
type CardElementButtonType string

// CardElementDivider defines model for CardElementDivider.
type CardElementDivider struct {
	Type CardElementDividerType `json:"type"`
}

// CardElementDividerType defines model for CardElementDivider.Type.
type CardElementDividerType string

// CardElementHeading defines model for CardElementHeading.
type CardElementHeading struct {
	Level uint8                  `json:"level"`
	Text  string                 `json:"text"`
	Type  CardElementHeadingType `json:"type"`
}

// CardElementHeadingType defines model for CardElementHeading.Type.
type CardElementHeadingType string

// CardElementLink defines model for CardElementLink.
type CardElementLink struct {
	Label string              `json:"label"`
	Type  CardElementLinkType `json:"type"`
	URL   string              `json:"url"`
}

// CardElementLinkType defines model for CardElementLink.Type.
type CardElementLinkType string

// CardElementList defines model for CardElementList.
type CardElementList struct {
	Items []ListItem          `json:"items"`
	Type  CardElementListType `json:"type"`
}

// CardElementListType defines model for CardElementList.Type.
type CardElementListType string

// CardElementProgress defines model for CardElementProgress.
type CardElementProgress struct {
	Label string                  `json:"label"`
	Type  CardElementProgressType `json:"type"`
	Value float64                 `json:"value"`
}

// CardElementProgressType defines model for CardElementProgress.Type.
type CardElementProgressType string

// CardElementTerm defines model for CardElementTerm.
type CardElementTerm struct {
	Gloss   *string             `json:"gloss,omitempty"`
	Lang    *string             `json:"lang,omitempty"`
	Reading *string             `json:"reading,omitempty"`
	Type    CardElementTermType `json:"type"`
	Word    string              `json:"word"`
}

// CardElementTermType defines model for CardElementTerm.Type.
type CardElementTermType string

// CardElementText defines model for CardElementText.
type CardElementText struct {
	Lang *string             `json:"lang,omitempty"`
	Text string              `json:"text"`
	Type CardElementTextType `json:"type"`
}

// CardElementTextType defines model for CardElementText.Type.
type CardElementTextType string

// ContextSliceLanguages defines model for ContextSliceLanguages.
type ContextSliceLanguages struct {
	Kind       ContextSliceLanguagesKind `json:"kind"`
	Level      *uint8                    `json:"level,omitempty"`
	SourceLang string                    `json:"source_lang"`
	TargetLang string                    `json:"target_lang"`
}

// ContextSliceLanguagesKind defines model for ContextSliceLanguages.Kind.
type ContextSliceLanguagesKind string

// ContextSlicePlanSummary defines model for ContextSlicePlanSummary.
type ContextSlicePlanSummary struct {
	Kind          ContextSlicePlanSummaryKind `json:"kind"`
	PlanID        string                      `json:"plan_id"`
	SetCount      uint32                      `json:"set_count"`
	SetsCompleted uint32                      `json:"sets_completed"`
	TargetLang    string                      `json:"target_lang"`
	Title         *string                     `json:"title,omitempty"`
}

// ContextSlicePlanSummaryKind defines model for ContextSlicePlanSummary.Kind.
type ContextSlicePlanSummaryKind string

// ContextSliceReviewDue defines model for ContextSliceReviewDue.
type ContextSliceReviewDue struct {
	Due     uint32                    `json:"due"`
	Kind    ContextSliceReviewDueKind `json:"kind"`
	Learned uint32                    `json:"learned"`
}

// ContextSliceReviewDueKind defines model for ContextSliceReviewDue.Kind.
type ContextSliceReviewDueKind string

// ContextSliceTutorTopic defines model for ContextSliceTutorTopic.
type ContextSliceTutorTopic struct {
	Kind  ContextSliceTutorTopicKind `json:"kind"`
	Topic string                     `json:"topic"`
}

// ContextSliceTutorTopicKind defines model for ContextSliceTutorTopic.Kind.
type ContextSliceTutorTopicKind string

// ListItemTerm defines model for ListItemTerm.
type ListItemTerm struct {
	Gloss   *string          `json:"gloss,omitempty"`
	Lang    *string          `json:"lang,omitempty"`
	Reading *string          `json:"reading,omitempty"`
	Type    ListItemTermType `json:"type"`
	Word    string           `json:"word"`
}

// ListItemTermType defines model for ListItemTerm.Type.
type ListItemTermType string

// ListItemText defines model for ListItemText.
type ListItemText struct {
	Lang *string          `json:"lang,omitempty"`
	Text string           `json:"text"`
	Type ListItemTextType `json:"type"`
}

// ListItemTextType defines model for ListItemText.Type.
type ListItemTextType string
