# frozen_string_literal: true

# ruby/codegen/generate.rb — the half of the Ruby kit openapi-generator does
# not write (ADR 30.9.26am D6). It reads the app view
# (spec/generator/apps.3.0.json) and VERSION, and writes three files into
# lib/lingara/apps/ (or --out <dir>):
#
#   unions.rb      the three sealed unions from x-lingara-unions, each a
#                  module its arms include (`case x in Lingara::Apps::CardElement`
#                  matches any arm), one Data class per arm with the arm's
#                  closed member set and its wire form, the tag-to-arm table,
#                  and CONTEXT_SLICE_KINDS, the ContextSlice tag values the
#                  manifest builder's `context` reads
#   operations.rb  x-lingara-app-operations: the request messages
#                  (`app.render`, `app.action`), each one's generated request
#                  model, and the reply message `app.card`
#   version.rb     VERSION, GEM_VERSION and GENERATED_FROM
#
# It refuses a models directory (--models, by default openapi-generator's
# lib/lingara/apps/generated/) holding a file named after a union or an arm
# it writes: codegen/ruby.openapi-generator-ignore names them, and a fourth
# union or a new arm it does not name would otherwise ship two types for one
# name. Standard library only; not shipped in the gem.

require "fileutils"
require "json"
require "optparse"

module LingaraAppsCodegen
  ROOT = File.expand_path("../..", __dir__)
  HEADER = "# Generated by ruby/codegen/generate.rb from the app view. DO NOT EDIT.\n"

  module_function

  def snake(name)
    name.gsub(/([a-z\d])([A-Z])/, '\1_\2').gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2').downcase
  end

  def ref_name(ref)
    ref.to_s.split("/").last
  end

  # RubyGems' spelling of a SemVer pre-release: every `-` becomes `.pre.`,
  # as Gem::Version itself does.
  def gem_version(version)
    version.gsub("-", ".pre.")
  end

  # Each union: its name, tag and arms, every arm with its wire tag value,
  # its class name and its members (required first, in the view's order;
  # the tag is the arm's own, so never a member).
  def unions(view)
    schemas = view.dig("components", "schemas") || {}
    view.fetch("x-lingara-unions").map do |union|
      tag = union.fetch("tag")
      arms = union.fetch("arms").map do |arm|
        name = ref_name(arm.fetch("schema"))
        schema = schemas[name] || abort("generate.rb: #{union["name"]}'s arm #{name} is not a component")
        {value: arm.fetch("value"), name: name, members: members(schema, tag)}
      end
      {name: union.fetch("name"), tag: tag, arms: arms}
    end
  end

  def members(schema, tag)
    required = Array(schema["required"])
    names = schema.fetch("properties", {}).keys - [tag]
    names.map { |n| {name: n, required: required.include?(n)} }.sort_by { |m| m[:required] ? 0 : 1 }
  end

  def operations(view)
    view.fetch("x-lingara-app-operations").map do |op|
      {message: op.fetch("message"), request: ref_name(op.fetch("request")), reply: op.fetch("reply_message")}
    end
  end

  # A message's constant: `app.render` is RENDER.
  def const_name(message)
    message.split(".").last.upcase.tr("-", "_")
  end

  def unions_rb(unions)
    kinds = unions.find { |u| u[:name] == "ContextSlice" } || abort("generate.rb: the view has no ContextSlice union")
    <<~RUBY
      #{HEADER.chomp}

      module Lingara
        module Apps
          # The helpers every arm below shares.
          module Unions
            # An arm's wire form: its tag, then every member that is set (an
            # unset optional member is omitted, never null), nested arms in
            # their own wire form.
            def self.wire(tag, value, members)
              members.compact.each_with_object({tag => value}) do |(name, member), out|
                out[name.to_s] = member.is_a?(Array) ? member.map { |m| m.respond_to?(:to_wire) ? m.to_wire : m } : member
              end
            end

            # The keyword arguments for an arm, read from a decoded JSON
            # object: its own members only (an unknown key is ignored), null
            # treated as absent. A missing required member is ArgumentError.
            def self.members(arm, fields)
              arm.members.to_h { |m| [m, fields[m.to_s]] }.compact
            end
          end

      #{unions.map { |u| union_module(u) }.join("\n")}
      #{unions.flat_map { |u| u[:arms].map { |a| arm_class(u, a) } }.join("\n")}
      #{unions.map { |u| union_table(u) }.join("\n")}
          # The ContextSlice tag values, in the view's order: what a manifest's
          # `context` may name.
          CONTEXT_SLICE_KINDS = #{kinds[:arms].map { |a| a[:value] }.inspect}.freeze
        end
      end
    RUBY
  end

  def union_module(union)
    <<~RUBY.gsub(/^(?=.)/, "    ")
      # A #{union[:name]}, tagged on `#{union[:tag]}`: every arm includes this module, so
      # `case x in Lingara::Apps::#{union[:name]}` matches any of them.
      module #{union[:name]}
      end
    RUBY
  end

  def arm_class(union, arm)
    members = arm[:members]
    symbols = members.map { |m| ":#{m[:name]}" }.join(", ")
    lines = ["# The #{union[:name]} arm `#{arm[:value]}`.", "#{arm[:name]} = Data.define(#{symbols}) do", "  include #{union[:name]}", ""]
    if members.any? { |m| !m[:required] }
      params = members.map { |m| m[:required] ? "#{m[:name]}:" : "#{m[:name]}: nil" }.join(", ")
      lines += ["  def initialize(#{params})", "    super", "  end", ""]
    end
    lines += [
      "  def #{union[:tag]} = #{arm[:value].inspect}", "",
      "  def to_wire = Unions.wire(#{union[:tag].inspect}, #{arm[:value].inspect}, to_h)", "",
      "  def self.from_wire(fields) = new(**Unions.members(self, fields))", "end"
    ]
    "#{lines.map { |l| l.empty? ? "" : "    #{l}" }.join("\n")}\n"
  end

  def union_table(union)
    rows = union[:arms].map { |a| "    #{a[:value].inspect} => #{a[:name]}" }.join(",\n")
    <<~RUBY.gsub(/^(?=.)/, "    ")
      module #{union[:name]}
        TAG = #{union[:tag].inspect}

        # Each tag value's arm.
        ARMS = {
      #{rows}
        }.freeze

        # The arm a decoded JSON object names, or nil for a tag this kit does
        # not know. A known arm missing a required member is ArgumentError.
        def self.decode(fields)
          arm = ARMS[fields[TAG]]
          arm&.from_wire(fields)
        end
      end
    RUBY
  end

  def operations_rb(ops)
    requests = ops.map { |op| "        #{op[:message].inspect} => #{op[:request].inspect}" }.join(",\n")
    consts = ops.map { |op| "      #{const_name(op[:message])} = #{op[:message].inspect}" }.join("\n")
    replies = ops.map { |op| op[:reply] }.uniq
    abort("generate.rb: the operations reply with more than one message: #{replies.inspect}") unless replies.size == 1
    <<~RUBY
      #{HEADER.chomp}

      module Lingara
        module Apps
          # The view's x-lingara-app-operations: the request messages a kit
          # dispatches on (a request's `type`) and the reply message. The core's
          # dispatch table is held to REQUESTS' keys by a unit test, so a third
          # operation fails the build until the core handles it.
          module Operations
      #{consts}

            # Each request message and the name of its generated request model.
            REQUESTS = {
      #{requests}
            }.freeze

            # The reply every request expects: a card.
            REPLY = #{replies.first.inspect}
          end
        end
      end
    RUBY
  end

  def version_rb(version, generated_from)
    <<~RUBY
      #{HEADER.chomp}

      module Lingara
        module Apps
          # This kit's released version, SemVer.
          VERSION = #{version.inspect}

          # The same version in RubyGems' spelling, which the gemspec uses.
          GEM_VERSION = #{gem_version(version).inspect}

          # The API version the app view was generated from.
          GENERATED_FROM = #{generated_from.inspect}
        end
      end
    RUBY
  end

  # openapi-generator's model named after a union or an arm would be a
  # second type under that name: they are this script's.
  def refuse_generated(models, unions)
    names = unions.flat_map { |u| [u[:name]] + u[:arms].map { |a| a[:name] } }
    names.each do |name|
      file = File.join(models, "#{snake(name)}.rb")
      next unless File.exist?(file)
      abort("generate.rb: #{file} is openapi-generator's model named after #{name}, which generate.rb writes; " \
            "name it in codegen/ruby.openapi-generator-ignore")
    end
  end

  def options(argv)
    out = File.join(ROOT, "ruby/lib/lingara/apps")
    opts = {out: out, models: nil, view: File.join(ROOT, "spec/generator/apps.3.0.json"), version: File.join(ROOT, "VERSION")}
    OptionParser.new do |o|
      o.on("--out DIR") { |v| opts[:out] = v }
      o.on("--models DIR") { |v| opts[:models] = v }
      o.on("--view FILE") { |v| opts[:view] = v }
      o.on("--version FILE") { |v| opts[:version] = v }
    end.parse!(argv)
    opts[:models] ||= File.join(opts[:out], "generated")
    opts
  end

  def run(argv)
    opts = options(argv)
    view = JSON.parse(File.read(opts[:view]))
    all = unions(view)
    refuse_generated(opts[:models], all)
    files = {
      "unions.rb" => unions_rb(all),
      "operations.rb" => operations_rb(operations(view)),
      "version.rb" => version_rb(File.read(opts[:version]).strip, view.dig("info", "version"))
    }
    FileUtils.mkdir_p(opts[:out])
    files.each { |name, text| File.write(File.join(opts[:out], name), text) }
  end
end

LingaraAppsCodegen.run(ARGV) if $PROGRAM_NAME == __FILE__
